backend:
  name: git-gateway
  branch: master

media_folder: /static/images
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Feature Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "page"
    label: "Page"
    folder: "content/page"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Feature Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "features"
    label: "Features"
    folder: "content/feature"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Feature Icon", name: "icon", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Full Screen", name: "fullScreen", widget: "boolean"}
  - name: "headers"
    label: "Headers"
    folder: "content/header"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "markdown"}
      - {label: "Background Image", name: "image", widget: "image"}
      - {label: "Button Text", name: "buttonText", widget: "string", required: false}
      - {label: "Button Link", name: "buttonLink", widget: "string", required: false}
      - {label: "Button Link External", name: "buttonLinkExternal", widget: "boolean", required: false}
  - name: "business"
    label: "Business"
    folder: "content/business"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Position", name: "position", widget: "number"}