backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Feature Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "features"
    label: "Features"
    folder: "content/features"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Feature Icon", name: "icon", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Full Screen", name: "fullScreen", widget: "boolean"}
  - name: "headers"
    label: "Headers"
    folder: "content/headers"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "markdown"}
      - {label: "Subtitle", name: "subtitle", widget: "markdown"}
      - {label: "Background Image", name: "image", widget: "image"}
      - {label: "Button Text", name: "buttonText", widget: "string"}
      - {label: "Button Link", name: "buttonLink", widget: "string"}
      - {label: "Button Link External", name: "buttonLinkExternal", widget: "boolean"}