backend:
  name: git-gateway
  branch: master

media_folder: static/images/blog
public_folder: /public

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Feature Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}